### PR TITLE
trading212 support (partial)

### PR DESCRIPTION
**Pull request by bobcho**
This adds support for parsing Trading212 statements in csv format in addition to Revolut's pdf statements. Just put all the files in the input folder.

Only partial support for time being - it lacks some activity types because I don't have a full statement at the moment (trading212 takes time to generate the statements and also I don't think I have received any dividends at all so far on their platform).

Includes support for market and limit buy/sell orders only (lacks anything else). Also, output/statements.csv won't have settlement date for trading212 activities as its not included in the t212 export. As settle date is not used anywhere I guess this is fine.

This should not break any current functionality or at least that was my intention.

### CODE REVIEW

**Comment by doino-gretchenliev** [comment]
Thank you for your PR. I'll review it soon.

**Comment by doino-gretchenliev** [comment]
I've reviewed the PR and I want to include your parser as supported. In order to develop infrastructure for other parsers, I've isolated the Revolut parser code [here](https://github.com/doino-gretchenliev/revolut-stocks/blob/main/libs/parsers/revolut.py). Please, rework your code to extend `StatementFilesParser` class and place it under `libs/parsers/trading212.py`. You can use the Revolut parser as an example. That way a user could call the app with `-s trading212` and use your parser.

**Comment by bobcho** [comment]
Thanks, added pr #10 with the rework.

I think there is the need to allow multiple -s arguments, allowing simultaneous parsing from multiple sources.

**Comment by doino-gretchenliev** [comment]
Agreed, I'll implement multiple sources.

**Comment by bobcho** [comment]
> Agreed, I'll implement multiple sources.

Looking forward to have this implemented :)

**Pull request closed without merging**
